# This is a basic workflow to help you get started with Actions

name: Super-Linter

on:push
 
jobs:
  super-lint:
    name: Checkout code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run Super-Linter
        uses: actions/super-linter@v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

